# The URL the site will be built for
base_url = "https://white-pond-03b06391e.1.azurestaticapps.net/"

title = "PDX BitDevs"
description = "PDX BitDevs is a community in the Portland, Oregon area for those interested in discussing and participating in the research and development of Bitcoin and related protocols and software."

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

generate_feeds = true
feed_filenames = ["atom.xml", "rss.xml"]

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

# Configuration of the Markdown rendering
[markdown]

# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
github = "https://github.com/Portland-Bit-Devs/"
meetup = "https://www.meetup.com/portlandbitdevs/"
telegram = "https://t.me??/PortlandBitDevs"
